FROM golang:alpine as builder
RUN apk update && apk add --no-cache git
RUN go get github.com/gorilla/mux
RUN go get github.com/savaki/jq
RUN mkdir /build 
ADD . /build/
WORKDIR /build 
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .
FROM scratch
COPY --from=builder /build/main /app/
WORKDIR /app
CMD ["./main"]
