FROM golang:alpine AS build-env
RUN apk update && apk add --no-cache git
ADD . /app
RUN cd /app 
RUN go get -d -v
RUN go build -o main

FROM alpine
WORKDIR /app
COPY --from=build-env /app/main /app/
ENTRYPOINT ./main
