apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
#  annotations:
#    kubernetes.io/ingress.class: "gce" #anc fixme what should this be?
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /*
        backend:
          servicePort: {{ .Values.httpPort }}
