apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stock-price-checker-ingress
  labels:
    app: stock-price-checker
#anc fixme do i need annotations?
spec:
  rules:
  - host: stockprice #minikube ip and add to hosts
    http:
      paths:
      - path: /*
        backend:
          servicePort: 80
          serviceName: stock-price-checker-service
