apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stock-price-checker-ingress
  labels:
    app: stock-price-checker
## don't appear to need the following annotation. why?
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: stockprice #minikube ip and add to hosts
    http:
      paths:
      - path: /*
        backend:
          servicePort: 80
          serviceName: stock-price-checker-service
