apiVersion: v1
kind: Service
metadata:
  name: stock-price-checker-service
spec:
  selector:
    app: stock-price-checker
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: stock-price-checker
