apiVersion: v1
kind: Service
metadata:
  name: stock-price-checker-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: stock-price-checker
  sessionAffinity: None
  type: ClusterIP
